In [ ]:
import pandas as pd

df = pd.read_excel("/content/HDR25_Statistical_Annex_GII_Table.xlsx", header=5)

df = df.dropna(axis=1, how='all')

df = df[df['Country'].notna()]

df.columns = df.columns.str.strip()

df.replace(['..', 'b', 'â€“'], pd.NA, inplace=True)

numeric_cols = df.columns.drop('Country')
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

df.head(10)

,HDI rank,Country,Unnamed: 2,Unnamed: 4,Unnamed: 6,Unnamed: 8,Unnamed: 10,Unnamed: 11,Female,Unnamed: 13,Male,Unnamed: 15,Female.1,Male.1
1,NaN,Very high human development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,Iceland,0.024,7.0,2.654418,3.369,47.619048,NaN,99.875916,NaN,99.582733,NaN,70.46,79.31
3,2.0,Norway,0.004,2.0,1.663741,1.405,46.153846,NaN,95.929504,NaN,98.505096,NaN,62.13,69.20
4,2.0,Switzerland,0.010,4.0,7.378755,1.483,37.804878,NaN,98.036560,NaN,98.324165,NaN,62.57,72.86
5,4.0,Denmark,0.003,1.0,4.657717,1.140,43.575419,NaN,90.998726,NaN,92.489220,NaN,59.70,67.70
6,5.0,Germany,0.057,21.0,4.428440,5.473,35.279503,NaN,93.591591,NaN,94.346039,NaN,56.41,66.72
7,5.0,Sweden,0.007,3.0,4.507839,1.792,46.418338,NaN,94.923492,NaN,94.123909,NaN,64.38,70.63
8,7.0,Australia,0.056,20.0,2.941509,6.715,44.493392,NaN,92.301262,NaN,93.453598,NaN,62.81,71.68
9,8.0,"Hong Kong, China (SAR)",NaN,NaN,NaN,1.120,NaN,NaN,77.870003,NaN,84.070000,NaN,52.24,63.59
10,8.0,Netherlands,0.013,5.0,4.311739,1.858,39.111111,NaN,91.073143,NaN,92.666412,NaN,64.08,73.09

In [ ]:
df.columns = [
    "HDI_rank", "Country", "GII_Value", "GII_Rank",
    "Maternal_mortality_ratio", "Adolescent_birth_rate",
    "Share_of_seats_in_parliament", "drop1",
    "Education_Female", "drop2", "Education_Male", "drop3",
    "Labour_Female", "Labour_Male"
]

df = df.drop(columns=["drop1", "drop2", "drop3"])

df = df[df["Country"].notna()]
df = df[df["Country"].str.contains("development") == False]

cols_to_num = df.columns.drop(["Country"])
df[cols_to_num] = df[cols_to_num].apply(pd.to_numeric, errors="coerce")

df.head()

,HDI_rank,Country,GII_Value,GII_Rank,Maternal_mortality_ratio,Adolescent_birth_rate,Share_of_seats_in_parliament,Education_Female,Education_Male,Labour_Female,Labour_Male
2,1.0,Iceland,0.024,7.0,2.654418,3.369,47.619048,99.875916,99.582733,70.46,79.31
3,2.0,Norway,0.004,2.0,1.663741,1.405,46.153846,95.929504,98.505096,62.13,69.20
4,2.0,Switzerland,0.010,4.0,7.378755,1.483,37.804878,98.036560,98.324165,62.57,72.86
5,4.0,Denmark,0.003,1.0,4.657717,1.140,43.575419,90.998726,92.489220,59.70,67.70
6,5.0,Germany,0.057,21.0,4.428440,5.473,35.279503,93.591591,94.346039,56.41,66.72

In [ ]:
for col in cols_to_fill:
    median_value = df[col].median()
    df[col] = df[col].fillna(median_value)


print(df.isna().sum())

HDI_rank                        0
Country                         0
GII_Value                       0
GII_Rank                        0
Maternal_mortality_ratio        0
Adolescent_birth_rate           0
Share_of_seats_in_parliament    0
Education_Female                0
Education_Male                  0
Labour_Female                   0
Labour_Male                     0
dtype: int64

In [ ]:
df['Education_gap'] = df['Education_Male'] - df['Education_Female']
df['Labour_gap'] = df['Labour_Male'] - df['Labour_Female']

In [ ]:
df['Education_GPI'] = df['Education_Female'] / df['Education_Male']
df['Labour_GPI'] = df['Labour_Female'] / df['Labour_Male']

In [ ]:
def hdi_group(rank):
    if rank <= 50:
        return 'Very High'
    elif rank <= 100:
        return 'High'
    elif rank <= 150:
        return 'Medium'
    else:
        return 'Low'

df['HDI_group'] = df['HDI_rank'].apply(hdi_group)

In [ ]:
df = df[['Country', 'HDI_rank', 'HDI_group', 'GII_Value',
         'Maternal_mortality_ratio', 'Adolescent_birth_rate',
         'Share_of_seats_in_parliament', 'Education_Female', 'Education_Male',
         'Education_gap', 'Education_GPI', 'Labour_Female', 'Labour_Male',
         'Labour_gap', 'Labour_GPI']]

In [ ]:
print(df.columns)

Index(['Country', 'HDI_rank', 'HDI_group', 'GII_Value',
       'Maternal_mortality_ratio', 'Adolescent_birth_rate',
       'Share_of_seats_in_parliament', 'Education_Female', 'Education_Male',
       'Education_gap', 'Education_GPI', 'Labour_Female', 'Labour_Male',
       'Labour_gap', 'Labour_GPI'],
      dtype='object')

In [ ]:
print(df.isna().sum())

Country                         0
HDI_rank                        0
HDI_group                       0
GII_Value                       0
Maternal_mortality_ratio        0
Adolescent_birth_rate           0
Share_of_seats_in_parliament    0
Education_Female                0
Education_Male                  0
Education_gap                   0
Education_GPI                   0
Labour_Female                   0
Labour_Male                     0
Labour_gap                      0
Labour_GPI                      0
dtype: int64

In [ ]:
print(df.dtypes)

Country                          object
HDI_rank                        float64
HDI_group                        object
GII_Value                       float64
Maternal_mortality_ratio        float64
Adolescent_birth_rate           float64
Share_of_seats_in_parliament    float64
Education_Female                float64
Education_Male                  float64
Education_gap                   float64
Education_GPI                   float64
Labour_Female                   float64
Labour_Male                     float64
Labour_gap                      float64
Labour_GPI                      float64
dtype: object

In [ ]:
df.head()

,Country,HDI_rank,HDI_group,GII_Value,Maternal_mortality_ratio,Adolescent_birth_rate,Share_of_seats_in_parliament,Education_Female,Education_Male,Education_gap,Education_GPI,Labour_Female,Labour_Male,Labour_gap,Labour_GPI
2,Iceland,1.0,Very High,0.024,2.654418,3.369,47.619048,99.875916,99.582733,-0.293182,1.002944,70.46,79.31,8.85,0.888413
3,Norway,2.0,Very High,0.004,1.663741,1.405,46.153846,95.929504,98.505096,2.575592,0.973853,62.13,69.20,7.07,0.897832
4,Switzerland,2.0,Very High,0.010,7.378755,1.483,37.804878,98.036560,98.324165,0.287605,0.997075,62.57,72.86,10.29,0.858770
5,Denmark,4.0,Very High,0.003,4.657717,1.140,43.575419,90.998726,92.489220,1.490494,0.983885,59.70,67.70,8.00,0.881832
6,Germany,5.0,Very High,0.057,4.428440,5.473,35.279503,93.591591,94.346039,0.754448,0.992003,56.41,66.72,10.31,0.845474

In [ ]:
#as csv
df.to_csv("GII_cleaned.csv", index=False)

In [ ]:
#as excel
df.to_excel("GII_cleaned.xlsx", index=False)